void reset_to_98(int *n);
unsigned int _strspn(char *s, char *accept);
char *cap_string(char *);
void reverse_array(int *a, int n);
int _strcmp(char *s1, char *s2);
char *_strcpy(char *dest, char *src);
void puts_half(char *str);
void print_rev(char *s);
int _putchar(char c);
int _strlen(char *s);
void swap_int(int *a, int *b);
